### ISSUE TITLE
ImportError: No module named robots

### ISSUE THREAD

**Issue by fili** [seomoz/reppy#60] opened 2017-02-28 21:05 UTC
When installing with pip on Linux in a sandbox, then trying to use the module I get the following error:

from reppy.robots import Robots
ImportError: No module named robots

**Comment by b4hand** [comment] 2017-02-28 22:08
Can you please include the definition of what you mean by sandbox? I just tried from a blank Ubuntu trusty64 vagrant box, and it works for me.

**Comment by fili** [comment] 2017-03-01 06:11
GAE standard environment: https://cloud.google.com/appengine/docs/standard/python/tools/using-libraries-python-27#installing_a_third-party_library

**Comment by b4hand** [comment] 2017-03-03 17:34
I'm guessing since this works on a completely vanilla Ubuntu image using Vagrant, that your issue is specific to Google's App Engine environment. Are you able to use *any* third-party packages? Maybe try using a different package than `reppy`.

**Comment by fili** [comment] 2017-03-03 19:49
A few packages that work fine within GAE: requests, urllib3, wtforms, pyopenssl, etc. 

Is your package a pure python module? I didn't see that information anywhere in the documentation. 

Thanks

**Comment by b4hand** [comment] 2017-03-03 19:52
No, current versions of reppy depend on rep-cpp and url-cpp using cython.

**Comment by b4hand** [comment] 2017-06-20 17:08
Resolving this as unable to reproduce, since we don't use GAE, and it seemingly works for others.

**Closed by b4hand** 2017-06-20 17:08 UTC
