### ISSUE TITLE
Problem with pip installation

### ISSUE THREAD

**Issue by wilima** [seomoz/reppy#56] opened 2017-02-09 13:09 UTC
Hello,

I have problem with pip installation (pip3.6)

```
Installing collected packages: reppy
  Running setup.py install for reppy ... error
    Complete output from command /Users/tomasmikula/.virtualenvs/upol/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/33/t1sr3dr97tgc5hj6b5pd90dh0000gn/T/pip-build-t9wjpdv7/reppy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/33/t1sr3dr97tgc5hj6b5pd90dh0000gn/T/pip-3zd6mk3q-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/tomasmikula/.virtualenvs/upol/bin/../include/site/python3.6/reppy:
    Building from C++
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.6
    creating build/lib.macosx-10.6-intel-3.6/reppy
    copying reppy/__init__.py -> build/lib.macosx-10.6-intel-3.6/reppy
    copying reppy/exceptions.py -> build/lib.macosx-10.6-intel-3.6/reppy
    copying reppy/ttl.py -> build/lib.macosx-10.6-intel-3.6/reppy
    copying reppy/util.py -> build/lib.macosx-10.6-intel-3.6/reppy
    creating build/lib.macosx-10.6-intel-3.6/reppy/cache
    copying reppy/cache/__init__.py -> build/lib.macosx-10.6-intel-3.6/reppy/cache
    copying reppy/cache/policy.py -> build/lib.macosx-10.6-intel-3.6/reppy/cache
    running build_ext
    building 'reppy.robots' extension
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/reppy
    creating build/temp.macosx-10.6-intel-3.6/reppy/rep-cpp
    creating build/temp.macosx-10.6-intel-3.6/reppy/rep-cpp/src
    creating build/temp.macosx-10.6-intel-3.6/reppy/rep-cpp/deps
    creating build/temp.macosx-10.6-intel-3.6/reppy/rep-cpp/deps/url-cpp
    creating build/temp.macosx-10.6-intel-3.6/reppy/rep-cpp/deps/url-cpp/src
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ireppy/rep-cpp/include -Ireppy/rep-cpp/deps/url-cpp/include -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c reppy/rep-cpp/src/agent.cpp -o build/temp.macosx-10.6-intel-3.6/reppy/rep-cpp/src/agent.o -std=c++11
    In file included from reppy/rep-cpp/src/agent.cpp:3:
    reppy/rep-cpp/deps/url-cpp/include/url.h:8:10: fatal error: 'unordered_map' file not found
    #include <unordered_map>
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/tomasmikula/.virtualenvs/upol/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/33/t1sr3dr97tgc5hj6b5pd90dh0000gn/T/pip-build-t9wjpdv7/reppy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/33/t1sr3dr97tgc5hj6b5pd90dh0000gn/T/pip-3zd6mk3q-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/tomasmikula/.virtualenvs/upol/bin/../include/site/python3.6/reppy" failed with error code 1 in /private/var/folders/33/t1sr3dr97tgc5hj6b5pd90dh0000gn/T/pip-build-t9wjpdv7/reppy/

```

**Comment by b4hand** [comment] 2017-02-09 17:37
This is not a problem with reppy. It's a problem with your build environment. [`<unordered_map>`](http://en.cppreference.com/w/cpp/container/unordered_map) is a standard C++ header, and the correct C++11 flag is being passed to clang, so it *should* be available. It's almost certainly an issue with your Xcode version. I believe there's an environment variable that you can set to use the correct version. Notice the build directory is named "macosx-10.6-intel-3.6". It's the 10.6 that is too old.

**Comment by b4hand** [comment] 2017-02-09 17:48
Duplicate of #45. I thought this was already brought up once before. It appears this [comment](https://github.com/seomoz/reppy/issues/45#issuecomment-272855851) was able to resolve the issue previously.

**Closed by b4hand** 2017-02-09 17:48 UTC
